⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/ci-iam-user-tf-module pull request #22
Opened 2021-06-02 21:52 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-tf-module.git`](https://github.com/cisagov/skeleton-tf-module.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/ci-iam-user-tf-module.git ci-iam-user-tf-module
    cd ci-iam-user-tf-module
    git remote add skeleton https://github.com/cisagov/skeleton-tf-module.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add README.md examples/basic_usage/README.md examples/basic_usage/main.tf examples/basic_usage/outputs.tf examples/basic_usage/variables.tf main.tf outputs.tf variables.tf 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may _append_ to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [ ] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2021-06-03 18:16 UTC, jsf9k approved these changes

2021-06-04 19:20 UTC, dav3r requested changes
There are some more tags to be removed - see https://github.com/cisagov/ci-iam-user-tf-module/search?q=var.tags

2021-06-04 19:29 UTC, dav3r approved these changes
🌶️

2021-07-08 19:18 UTC, mcdonnnj approved these changes
Just two variable descriptions to add periods to and then it LGTM 👍

2021-07-08 19:18 UTC, mcdonnnj commented on README.md
> +| production\_role\_tags | Extra tags to apply only to the production role resource | `map(string)` | `{"GitHub_Secret_Name": "TEST_ROLE_TO_ASSUME", "GitHub_Secret_Terraform_Lookup": "arn"}` | no |
```suggestion
| production\_role\_tags | Extra tags to apply only to the production role resource. | `map(string)` | `{"GitHub_Secret_Name": "TEST_ROLE_TO_ASSUME", "GitHub_Secret_Terraform_Lookup": "arn"}` | no |
```

2021-07-08 19:18 UTC, mcdonnnj commented on README.md
> +| staging\_role\_tags | Extra tags to apply only to the staging role resource | `map(string)` | `{}` | no |
```suggestion
| staging\_role\_tags | Extra tags to apply only to the staging role resource. | `map(string)` | `{}` | no |
```

2021-07-08 19:46 UTC, jsf9k commented on README.md
> +| production\_role\_tags | Extra tags to apply only to the production role resource | `map(string)` | `{"GitHub_Secret_Name": "TEST_ROLE_TO_ASSUME", "GitHub_Secret_Terraform_Lookup": "arn"}` | no |
See commit bbbbb73.

2021-07-08 19:47 UTC, jsf9k commented on README.md
> +| staging\_role\_tags | Extra tags to apply only to the staging role resource | `map(string)` | `{}` | no |
See commit bbbbb73.

2021-07-09 13:19 UTC, merged